### ISSUE TITLE
even mem_req=32GB , IOError: [Errno 32] Broken pipe

### ISSUE THREAD

**Issue by roko-t** [Genomon-Project/Genomon#47]
```

    STDOUT:
    STDERR:
Unable to initialize environment because of error:  error preparing signal handling thread
Exiting.


    star: runtask failed
    #star
Process LoggingManager-1:
Traceback (most recent call last):
  File "/usr/local/package/python2.7/current/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/local/package/python2.7/current/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/package/python2.7/current/lib/python2.7/multiprocessing/managers.py", line 558, in _run_server
    server.serve_forever()
  File "/usr/local/package/python2.7/current/lib/python2.7/multiprocessing/managers.py", line 184, in serve_forever
    t.start()
  File "/usr/local/package/python2.7/current/lib/python2.7/threading.py", line 745, in start
    qsub
    qsub
    qsub
    qsub
    qsub
    STDOUT:
    STDOUT:
    STDOUT: Couldn't create event client thread: Resource temporarily unavailableYour job 652119 ("star_20150727_1830_467255.sh") has been submitted

    STDOUT: Couldn't create event client thread: Resource temporarily unavailableYour job 652123 ("star_20150727_1830_487901.sh") has been submitted

    STDOUT: Couldn't create event client thread: Resource temporarily unavailableYour job 652124 ("star_20150727_1830_484429.sh") has been submitted

    _start_new_thread(self.__bootstrap, ())
error: can't start new thread
Traceback (most recent call last):
  File "/home/w3varann/tools/Genomon/genomon.py", line 465, in <module>
    main()
  File "/home/w3varann/tools/Genomon/genomon.py", line 451, in main
    log.error( "{0}: Unexpected error".format( whoami() ) )
  File "/home/w3varann/.local/lib/python2.7/site-packages/ruffus/proxy_logger.py", line 289, in error
    return self._callmethod('error', args, kwargs)
  File "/usr/local/package/python2.7/current/lib/python2.7/multiprocessing/managers.py", line 758, in _callmethod
    conn.send((self._id, methodname, args, kwds))
IOError: [Errno 32] Broken pipe
```

**Comment by eigoshimizu** [comment]
multiprocessing モジュールを使って、プロセスを立ち上げていたのですが、リソースが亡くなってしまったのだと思います。

qsub -sync y でプロセスを立ち上げているので、qsub で投入する場合は、さらにリソースを使ってしまっていると思います。

genomon.py に --drmaa と --use_threads を指定して、　DRMAAを使って、thread でジョブを投入すれば、かなり使用リソースを軽減できると思います。
よろしくお願いいたします。
とりあえず、クローズしますが、問題があると判断された場合は、再度オープンしてください。
よろしくお願いいたします。
