### ISSUE TITLE
genomon.py　のオプション--jobs に1000を設定するとIOError: [Errno 32] Broken pipe

### ISSUE THREAD

**Issue by roko-t** [Genomon-Project/Genomon#64]
尚、500なら正常動作

===============
```
/usr/local/package/python2.7/current/bin/python $3 /home/w3varann/tools/Genomon/genomon.py \
           --config_file /home/w3varann/tools/Genomon/samples/genomon.cfg \
           --job_file $1 \
           --param_file $2 \
           --jobs 1000 \
           --verbose 1 \
           --drmaa \
           --use_threads
+ /usr/local/package/python2.7/current/bin/python /home/w3varann/tools/Genomon/genomon.py --config_file /home/w3varann/tools/Genomon/samples/genomon.cfg --job_file config/CD274_RNA_150731_job_20150805_star.yaml --param_file config/CD274_RNA_150731_param_star_limitBAMsortRAM_31GB.yaml --jobs 1000 --verbose 1 --drmaa --use_threads

Generated by /home/w3varann/tools/Genomon/genomon.py
    Input config file = /home/w3varann/tools/Genomon/samples/genomon.cfg
    Input job file    = config/CD274_RNA_150731_job_20150805_star.yaml
    RunTask: run_mode=DRMAA

    ________________________________________
    Tasks which will be run:


    Task enters queue = 'helpers.star_pipeline.star'
Process LoggingManager-1:
Traceback (most recent call last):
  File "/usr/local/package/python2.7/current/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/local/package/python2.7/current/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/package/python2.7/current/lib/python2.7/multiprocessing/managers.py", line 558, in _run_server
    server.serve_forever()
  File "/usr/local/package/python2.7/current/lib/python2.7/multiprocessing/managers.py", line 184, in serve_forever
    t.start()
  File "/usr/local/package/python2.7/current/lib/python2.7/threading.py", line 745, in start
    _start_new_thread(self.__bootstrap, ())
error: can't start new thread
Traceback (most recent call last):
  File "/home/w3varann/tools/Genomon/genomon.py", line 519, in <module>
    main()
  File "/home/w3varann/tools/Genomon/genomon.py", line 511, in main
    log.error( "{0}: Unexpected error".format( whoami() ) )
  File "/home/w3varann/.local/lib/python2.7/site-packages/ruffus/proxy_logger.py", line 289, in error
    return self._callmethod('error', args, kwargs)
  File "/usr/local/package/python2.7/current/lib/python2.7/multiprocessing/managers.py", line 758, in _callmethod
    conn.send((self._id, methodname, args, kwds))
IOError: [Errno 32] Broken pipe
```

**Comment by eigoshimizu** [comment]
これに関しては、 並列時のリソースの問題です。
issue #63と同様な問題として処理したいと思います。
Closeさせていただきます。
