### ISSUE TITLE
sampleリスト実行でcPickle.PicklingError

### ISSUE THREAD

**Issue by aokad** [Genomon-Project/Genomon#95]
```
$ qlogin -l s_vmem=32G,mem_req=32G
$ ./Genomon DNA debug-work samples/sample.tsv
Traceback (most recent call last):
  File "./Genomon", line 669, in <module>
    main()
  File "./Genomon", line 657, in main
    log.error( e )
  File "/home/aiokada/.local/lib/python2.7/site-packages/ruffus/proxy_logger.py", line 289, in error
    return self._callmethod('error', args, kwargs)
  File "/usr/local/package/python2.7/2.7.2/lib/python2.7/multiprocessing/managers.py", line 758, in _callmethod
    conn.send((self._id, methodname, args, kwds))
cPickle.PicklingError: Can't pickle <type 'function'>: attribute lookup __builtin__.function failed
```

**Comment by eigoshimizu** [comment]
このエラーは、multiprocessingのリソースの問題です。
Genomonの中で、sample.tsvの中にあるサンプルの数で、並列度をしていして、 ruffusを実行します。

sample.tsvをいただけませんか？

**Comment by aokad** [comment]
sample.tsvはsamplesディレクトリのもので変更していません。

**Comment by ken0-1n** [comment]
close
